---
site_name: Kori Hanes - Home Lab Build Guide
site_description: DevSecOps & GitOps Portfolio
site_url: https://homelab.koriwayne.com
repo_url: https://github.com/KurhyWns/homelab.koriwayne.com
repo_name: KurhyWns/homelab.koriwayne.com

extra_css:
  - assets/css/extra.css

theme:
  name: material
  palette:
    # Dark theme
    scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md
  - Projects:
      - Homelab Project:
          - Overview: projects/homelab/index.md
  - Documentation:
      - Gitea: gitea/index.md
      - MetalLB: metallb/index.md
      - ArgoCD: argocd/index.md
  - Development:
      - Branching Strategy: branching-strategy/index.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html

plugins:
  - search
